name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Snyk Security Scan
      working-directory: ./src/
      run: |
        pip install -r requirements.txt
        npm install -g snyk
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build Docker image
      run: docker build -t ayanchev/python-app:latest .

    - name: Scan the Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ayanchev/python-app:latest'
        format: 'table'
        exit-code: '1'
        severity: 'HIGH,CRITICAL'

    - name: Push Docker image
      if: success()
      run: docker push ayanchev/python-app:latest